export const COIN_NAMES: Record<string, string> = {
  "1000CAT": "1000*Simons Cat",
  "1000CHEEMS": "1000*cheems.pet",
  "1000SATS": "1000*SATS(Ordinals)",
  "1INCH": "1inch",
  "1MBABYDOGE": "1M x BABYDOGE",
  "2Z": "DoubleZero",
  "A": "Vaulta",
  "A2Z": "Arena-Z",
  "AAVE": "Aave",
  "ACA": "Acala Token",
  "ACE": "Fusionist",
  "ACH": "Alchemy Pay",
  "ACM": "AC Milan Fan Token",
  "ACT": "Act I: The AI Prophecy",
  "ACX": "Across Protocol",
  "ADA": "Cardano",
  "ADX": "AdEx",
  "AEUR": "Anchored EUR",
  "AEVO": "AEVO",
  "AGLD": "Adventure Gold",
  "AI": "Sleepless AI",
  "AIXBT": "aixbt by Virtuals",
  "ALCX": "Alchemix",
  "ALGO": "Algorand",
  "ALICE": "My Neighbor Alice",
  "ALLO": "Allora",
  "ALPINE": "Alpine F1 Team Fan Token",
  "ALT": "AltLayer",
  "AMP": "AMP",
  "ANIME": "Animecoin",
  "ANKR": "Ankr",
  "APE": "ApeCoin",
  "API3": "API3",
  "APT": "Aptos",
  "AR": "APRO",
  "ARB": "Arbitrum",
  "ARDR": "Ardor",
  "ARK": "Ark",
  "ARKM": "Arkham",
  "ARPA": "ARPA Network",
  "ASR": "AS Roma Fan Token",
  "ASTER": "Aster",
  "ASTR": "Astar",
  "ATA": "Automata",
  "ATM": "Atlético de Madrid Fan Token",
  "ATOM": "Cosmos",
  "AUCTION": "Auction",
  "AUDIO": "Audius",
  "AVA": "AVA",
  "AVAX": "Avalanche",
  "AVNT": "Avantis",
  "AWE": "AWE Network",
  "AXL": "Axelar",
  "AXS": "Axie Infinity",
  "BABY": "Babylon",
  "BANANA": "Banana Gun",
  "BANANAS31": "Banana For Scale",
  "BAND": "BAND",
  "BANK": "Lorenzo Protocol",
  "BAR": "FC Barcelona Fan Token BAR",
  "BARD": "Lombard",
  "BAT": "Basic Attention Token",
  "BB": "BounceBit",
  "BCH": "Bitcoin Cash",
  "BEAMX": "BEAM (Formerly Merit Circle)",
  "BEL": "Bella Protocol",
  "BERA": "BERACHAIN",
  "BFUSD": "BFUSD",
  "BICO": "Biconomy",
  "BIFI": "Beefy.Finance",
  "BIGTIME": "BigTime",
  "BIO": "Bio Protocol",
  "BLUR": "Blir",
  "BMT": "Bubllemaps",
  "BNB": "BNB",
  "BNSOL": "Binance Staked SOL",
  "BNT": "Bancor",
  "BOME": "BOOK OF MEME",
  "BONK": "Bonk",
  "BROCCOLI714": "CZ'S Dog (broccoli.ngo)",
  "BTTC": "BitTorrent",
  "BTC": "Bitcoin",
  "C": "Chainbase",
  "C98": "Coin98",
  "CAKE": "PancakeSwap",
  "CATI": "Catizen",
  "CELO": "Celo",
  "CELR": "Celer Network",
  "CETUS": "Cetus Protocol",
  "CFX": "Conflux Network",
  "CGPT": "ChainGPT",
  "CHESS": "Tranchess",
  "CHR": "Chromia",
  "CHZ": "Chiliz",
  "CITY": "Manchester City Fan Token",
  "CKB": "CKB",
  "COMP": "Compound",
  "COOKIE": "Cookie DAO",
  "COS": "Contentos",
  "COTI": "COTI",
  "COW": "CoW Protocol",
  "CRV": "Curve",
  "CTK": "Shentu",
  "CTSI": "Cartesi",
  "CVC": "Civic",
  "CVX": "Convex Finance",
  "CYBER": "Cyber",
  "D": "Dar Open Network",
  "DAI": "Dai",
  "DATA": "Streamr",
  "DCR": "Decred",
  "DEGO": "Dego Finance",
  "DENT": "DENT",
  "DEXE": "DeXe",
  "DF": "dForce",
  "DIA": "DIA",
  "DODO": "DODO",
  "DOGS": "Dogs",
  "DOLO": "Dolomite",
  "DOT": "Polkadot",
  "DUSK": "Dusk",
  "DYDX": "dYdX",
  "DYM": "Dymension",
  "EDEN": "OpenEden",
  "EDU": "Open Campus",
  "EGLD": "MultiversX",
  "EIGEN": "EigenLayer",
  "ENA": "Ehena",
  "ENJ": "Enjin Coin",
  "ENS": "Ethereum Name Service",
  "ENSO": "Enso",
  "EPIC": "Epic Chain",
  "ERA": "Caldera",
  "ETC": "Ethereum Classic",
  "ETH": "Ethereum",
  "ETHFI": "ether.fi",
  "EUL": "Euler",
  "EURI": "Eurite",
  "F": "SynFutures",
  "FARM": "Harvest Finance",
  "FDUSD": "First Digital USD",
  "FET": "Artificial Superintelligence Alliance",
  "FF": "Falcon Finance",
  "FIDA": "Bonfida",
  "FIL": "Filecoin",
  "FIO": "FIO Protocol",
  "FLOKI": "FLOKI",
  "FLOW": "Flow",
  "FLUX": "Flux",
  "FORM": "Four",
  "FORTH": "Ampleforth Governance Token",
  "FFT": "FTX Token",
  "FUN": "FunToken",
  "FXS": "Frax Share",
  "G": "Gravity",
  "GALA": "Gala",
  "GAS": "NeoGas",
  "GHST": "Aavegotchi",
  "GIGGLE": "Giggle Fund",
  "GLM": "Golem",
  "GLMR": "Glimmer",
  "GMT": "Green Metaverse Token",
  "GMX": "GMX",
  "GNO": "Gnosis",
  "GS": "Gains Network",
  "GPS": "GoPlus Security",
  "GRT": "The Graph",
  "GTC": "Gitcoin",
  "GUN": "GUNZ",
  "HAEDAL": "Haedal",
  "HBAR": "Hedera Hashgraph",
  "HEI": "Heima",
  "HEMI": "HEMI",
  "HTF": "Hashflor",
  "HIGH": "Highstreet",
  "HIVE": "Hive",
  "HMSTR": "Hasmter Kombat",
  "HOLO": "Holoword AI",
  "HOME": "Defi App",
  "HOOK": "Hooked Protocol",
  "HOT": "Holo",
  "HUMA": "Huma Finance",
  "HYPER": "Hyperlane",
  "ICP": "Internet Computer",
  "ICX": "ICON",
  "ID": "Space ID",
  "IDEX": "IDEX",
  "ILV": "Illuvium",
  "IMX": "ImmutableX",
  "INIT": "Initia",
  "INJ": "Injective",
  "IO": "IO.NET",
  "IOST": "IOST",
  "IOTA": "IOTA",
  "IOTX": "IoTeX",
  "IQ": "IQ",
  "JASMY": "JasmyCoin",
  "JOE": "JOE",
  "JST": "JUST",
  "JTO": "JITO",
  "JUO": "Jupiter",
  "JUV": "Juventus Fan Token",
  "KAIA": "Kaia",
  "KAITO": "Kaito",
  "KAVA": "Kava",
  "KERNEL": "KernelDAO",
  "KITE": "KITE",
  "KMNO": "Kamino Finance",
  "KNC": "KyberNetwork",
  "KMS": "Kusama",
  "LA": "Lagrange",
  "LAYER": "Solayer",
  "LAZIO": "Lazio Fan Token",
  "LDO": "Lido DAO",
  "LINEA": "Linea",
  "LINK": "ChainLink",
  "LISTA": "Lista",
  "LPT": "Livepeer",
  "LQTY": "Liquity",
  "LRC": "Loopring",
  "LSK": "Lisk",
  "LUMIA": "LUMIA",
  "LUNA": "Terra",
  "LUNC": "Terra Classic",
  "MAGIC": "Treasure",
  "MANA": "Decentraland",
  "MANTA": "Manta",
  "MASK": "Mask Network",
  "MAV": "Maverick Protocol",
  "MBL": "MovieBloc",
  "MBOX": "MOBOX",
  "MDT": "Measurable Data Token",
  "ME": "Magic Eden",
  "MEME": "Memecoin",
  "MET": "Meteora",
  "METIS": "MetisDAO",
  "MINA": "Mina",
  "MIRA": "Mira",
  "MITO": "Mitosis",
  "MLN": "Enzyme",
  "MMT": "Momentum",
  "MORPHO": "Morpho Token",
  "MOVE": "Movement",
  "MOR": "Moonriver",
  "MTL": "Metal DAO",
  "MUBARAK": "Mubarak",
  "NEAR": "NEAR Protocol",
  "NEIRO": "First Neiro On Ethereum",
  "NEO": "NEO",
  "NEWT": "Newton Protocol",
  "NEXO": "Nexo",
  "NFP": "NFPrompt Token",
  "NIL": "Nillion",
  "NKN": "NKN",
  "NMR": "Numeraire",
  "NOM": "Nomina",
  "NOT": "Notcoin",
  "NTRN": "Neutron",
  "NXPC": "Nexpace",
  "OG": "OG Fan Token",
  "OGN": "OriginToken",
  "OM": "MANTRA",
  "ONDO": "Ondo",
  "ONE": "Harmony",
  "ONG": "Ontology Gas",
  "ONT": "Ontology",
  "OP": "Optimism",
  "OPEN": "OpenLedger",
  "ORCA": "Orca",
  "ORDI": "ORDI",
  "OSMO": "Osmosis",
  "OXT": "Orchid",
  "PARTI": "Particle Network",
  "PAXG": "PAX Gold",
  "PENDLE": "Pendle",
  "PENGU": "Pudgy Penguins",
  "PEOPLE": "ConstitutionDAO",
  "PEPE": "Pepe",
  "PHA": "Phala.Network",
  "PHB": "Phoenix",
  "PIVX": "PIVX",
  "PIXEL": "Pïxels",
  "PLUME": "PLUME",
  "PNUT": "Peanut the Squirrel",
  "POL": "Polygon Ecosystem Token",
  "POLYX": "Polymesh",
  "POND": "Marlin",
  "PORTAL": "Portal",
  "PORTO": "FC Porto Fan Token",
  "POWR": "Powerledger",
  "PROM": "Prometeus",
  "PROVE": "Succint",
  "PSG": "Paris Saint-Germain Fan Token",
  "PUMP": "Pump.Fun",
  "PUNDIX": "PundiX",
  "PYR": "Vulcan Forged PYR",
  "PYTH": "Pyth Network",
  "QI": "BENQI",
  "QKC": "QuarkChain",
  "QNT": "Quant",
  "QTUM": "Qtum",
  "QUICK": "QuickSwap",
  "RAD": "Radworks",
  "RARE": "SuperRare",
  "RAY": "Raydium",
  "RDNT": "Radiant Capital",
  "RED": "RedStone",
  "RENDER": "Render",
  "REQ": "Request Network",
  "RESOLV": "Resolv",
  "REZ": "Renzo",
  "RIF": "Rootstock Infrastructure Framework",
  "RLC": "iExecRLC",
  "RONIN": "Ronin",
  "ROSE": "Oasis Network",
  "RPL": "RocketPool",
  "RSR": "Reserve Rights",
  "RUNE": "THORChain",
  "RVN": "Ravencoin",
  "S": "Sonic",
  "SAGA": "Saga",
  "SAHARA": "Sahara AI",
  "SAND": "The Sandbox",
  "SANTOS": "Santos FC Fan Token",
  "SAPIEN": "SAPIEN",
  "SC": "Siacoin",
  "SCR": "Scroll",
  "SCRT": "secret",
  "SEI": "sei",
  "SFP": "SafePal",
  "SHELL": "MyShell",
  "SHIB": "SHIBA INU",
  "SIGN": "Sign",
  "SKL": "SKALE Network",
  "SKY": "Sky",
  "SLP": "Smooth Love Potion",
  "SNX": "Synthetix Network Token",
  "SOL": "Solana",
  "SOLV": "Solv Protocol",
  "SOMI": "Somnia",
  "SOPH": "Sophon",
  "SPELL": "Spell Token",
  "SPK": "Spark",
  "SSV": "SSV Token",
  "STEEM": "Steem",
  "STG": "Stargate Finance",
  "STO": "StakeStone",
  "STORJ": "Storj",
  "STRAX": "Stratis",
  "STRK": "Starknet Token",
  "STX": "Stacks",
  "SUI": "Sui",
  "SUN": "SUN",
  "SUPER": "SuperVerse",
  "SUSHI": "Sushi",
  "SXP": "Solar",
  "SXT": "Space and Time",
  "SYN": "Synapse",
  "SYRUP": "Maple Finance",
  "SYS": "Syscoin",
  "T": "Threshold",
  "TAO": "Bittensor",
  "TFUEL": "Theta Fuel",
  "THE": "THENA",
  "THETA": "Theta Token",
  "TIA": "Celestia",
  "TKO": "Tokocrypto",
  "TLM": "Alien Worlds",
  "TNSR": "Tensor",
  "TON": "Toncoin",
  "TOWNS": "Towns Protocol",
  "TRB": "Tellor Tributes",
  "TREE": "Treehouse",
  "TRU": "TrueFi",
  "TRUMP": "OFFICIAL TRUMP",
  "TRX": "TRON",
  "TST": "Test",
  "TURBO": "Turbo",
  "TURTLE": "Turtle",
  "TUSD": "TrueUSD",
  "TUT": "Tutorial",
  "TWT": "Trust Wallet Token",
  "UMA": "UMA",
  "UNI": "Uniswap",
  "USD1": "World Liberty Financial USD",
  "USDC": "USDC",
  "USDE": "USD Ethena",
  "USDP": "Pax Dollar",
  "USDT": "TetherUS",
  "USTC": "TerraClassicUSD",
  "USUAL": "Usual",
  "UTK": "xMoney",
  "VANA": "Vana",
  "VANRY": "Vanar",
  "VELODROME": "Velodrome Finance",
  "VET": "VeChain",
  "VIC": "Viction",
  "VIRTUAL": "Virtuals Protocol",
  "VTHO": "VeThor Token",
  "W": "Wormhole",
  "WAL": "Walrus",
  "WAN": "Wanchain",
  "WAXP": "WAX",
  "WBETH": "Wrapped Beacon ETH (WBETH)",
  "WBTC": "Wrapped Bitcoin",
  "WCT": "WalletConnect",
  "WIF": "Dogwifhat",
  "WIN": "WINkLink",
  "WLD": "Worldcoin",
  "WLFI": "World Liberty Financial",
  "WOO": "WOO",
  "XAI": "Xai",
  "XEC": "eCash",
  "XLM": "Stellar Lumens",
  "XNO": "Nano",
  "XPL": "Plasma",
  "XTZ": "Tezos",
  "XUSD": "XUSD",
  "XVG": "Verge",
  "XVS": "Venus",
  "YB": "Yield Basis",
  "YFI": "yearn.finance",
  "YGG": "Yield Guild Games",
  "ZBT": "Zerobase",
  "ZEC": "Zcash",
  "ZEN": "Horizen",
  "ZIL": "Zilliqa",
  "ZK": "zkSync",
  "ZKC": "Boundless",
  "ZRO": "LayerZero",
  "ZRX": "Ox"
}
  
